// Generated by gencpp from file voxel_mesh_msgs/facet.msg
// DO NOT EDIT!


#ifndef VOXEL_MESH_MSGS_MESSAGE_FACET_H
#define VOXEL_MESH_MSGS_MESSAGE_FACET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace voxel_mesh_msgs
{
template <class ContainerAllocator>
struct facet_
{
  typedef facet_<ContainerAllocator> Type;

  facet_()
    : header()
    , normal()
    , vi0(0)
    , vi1(0)
    , vi2(0)
    , color()
    , name(0)  {
      color.assign(0.0);
  }
  facet_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , normal(_alloc)
    , vi0(0)
    , vi1(0)
    , vi2(0)
    , color()
    , name(0)  {
  (void)_alloc;
      color.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _normal_type;
  _normal_type normal;

   typedef int32_t _vi0_type;
  _vi0_type vi0;

   typedef int32_t _vi1_type;
  _vi1_type vi1;

   typedef int32_t _vi2_type;
  _vi2_type vi2;

   typedef boost::array<float, 4>  _color_type;
  _color_type color;

   typedef int32_t _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::voxel_mesh_msgs::facet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voxel_mesh_msgs::facet_<ContainerAllocator> const> ConstPtr;

}; // struct facet_

typedef ::voxel_mesh_msgs::facet_<std::allocator<void> > facet;

typedef boost::shared_ptr< ::voxel_mesh_msgs::facet > facetPtr;
typedef boost::shared_ptr< ::voxel_mesh_msgs::facet const> facetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voxel_mesh_msgs::facet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voxel_mesh_msgs::facet_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace voxel_mesh_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'voxel_mesh_msgs': ['/home/brhm/DUC/RobotArm/src/voxel_mesh_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::voxel_mesh_msgs::facet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voxel_mesh_msgs::facet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voxel_mesh_msgs::facet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voxel_mesh_msgs::facet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voxel_mesh_msgs::facet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voxel_mesh_msgs::facet_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voxel_mesh_msgs::facet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9996c5663ca76b4deec6fe21ffe2f3d7";
  }

  static const char* value(const ::voxel_mesh_msgs::facet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9996c5663ca76b4dULL;
  static const uint64_t static_value2 = 0xeec6fe21ffe2f3d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::voxel_mesh_msgs::facet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voxel_mesh_msgs/facet";
  }

  static const char* value(const ::voxel_mesh_msgs::facet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voxel_mesh_msgs::facet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Vector3 normal\n\
int32 vi0\n\
int32 vi1\n\
int32 vi2\n\
float32[4] color\n\
int32 name\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::voxel_mesh_msgs::facet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voxel_mesh_msgs::facet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.normal);
      stream.next(m.vi0);
      stream.next(m.vi1);
      stream.next(m.vi2);
      stream.next(m.color);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct facet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voxel_mesh_msgs::facet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voxel_mesh_msgs::facet_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "normal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.normal);
    s << indent << "vi0: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vi0);
    s << indent << "vi1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vi1);
    s << indent << "vi2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vi2);
    s << indent << "color[]" << std::endl;
    for (size_t i = 0; i < v.color.size(); ++i)
    {
      s << indent << "  color[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.color[i]);
    }
    s << indent << "name: ";
    Printer<int32_t>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOXEL_MESH_MSGS_MESSAGE_FACET_H
