la_sr_ur_controller:
  type: sr_ur_controller/UrArmController
  
  # ra for right side arm la for left side arm
  robot_id: la
  
  # for sending robot programs
  robot_ip_address: 192.168.1.1
  
  # for the server that moves the robot 
  control_pc_ip_address: 192.168.1.100