/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file c:\work\ws\kinect_utils\body_msgs\msg\Skeletons.msg
 *
 */


#ifndef BODY_MSGS_MESSAGE_SKELETONS_H
#define BODY_MSGS_MESSAGE_SKELETONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <body_msgs/Skeleton.h>

namespace body_msgs
{
template <class ContainerAllocator>
struct Skeletons_
{
  typedef Skeletons_<ContainerAllocator> Type;

  Skeletons_()
    : header()
    , skeletons()  {
    }
  Skeletons_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , skeletons(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::body_msgs::Skeleton_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::body_msgs::Skeleton_<ContainerAllocator> >::other >  _skeletons_type;
  _skeletons_type skeletons;




  typedef boost::shared_ptr< ::body_msgs::Skeletons_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::body_msgs::Skeletons_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Skeletons_

typedef ::body_msgs::Skeletons_<std::allocator<void> > Skeletons;

typedef boost::shared_ptr< ::body_msgs::Skeletons > SkeletonsPtr;
typedef boost::shared_ptr< ::body_msgs::Skeletons const> SkeletonsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::body_msgs::Skeletons_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::body_msgs::Skeletons_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace body_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometric_shapes_msgs': ['c:/work/ws/geometric_shapes_msgs/msg'], 'std_msgs': ['c:/work/ws/std_msgs/msg'], 'body_msgs': ['c:/work/ws/kinect_utils/body_msgs/msg', 'c:/work/ws/kinect_utils/body_msgs/msg'], 'geometry_msgs': ['c:/work/ws/geometry_msgs/msg'], 'sensor_msgs': ['c:/work/ws/sensor_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::body_msgs::Skeletons_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::body_msgs::Skeletons_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::body_msgs::Skeletons_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::body_msgs::Skeletons_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::body_msgs::Skeletons_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::body_msgs::Skeletons_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::body_msgs::Skeletons_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d6667331403917cc53d8d820001e6f9";
  }

  static const char* value(const ::body_msgs::Skeletons_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d6667331403917cULL;
  static const uint64_t static_value2 = 0xc53d8d820001e6f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::body_msgs::Skeletons_<ContainerAllocator> >
{
  static const char* value()
  {
    return "body_msgs/Skeletons";
  }

  static const char* value(const ::body_msgs::Skeletons_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::body_msgs::Skeletons_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
body_msgs/Skeleton[] skeletons\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: body_msgs/Skeleton\n\
int32 playerid\n\
body_msgs/SkeletonJoint head\n\
body_msgs/SkeletonJoint neck\n\
body_msgs/SkeletonJoint right_hand\n\
body_msgs/SkeletonJoint left_hand\n\
body_msgs/SkeletonJoint right_shoulder\n\
body_msgs/SkeletonJoint left_shoulder\n\
body_msgs/SkeletonJoint right_elbow\n\
body_msgs/SkeletonJoint left_elbow\n\
body_msgs/SkeletonJoint torso\n\
body_msgs/SkeletonJoint left_hip\n\
body_msgs/SkeletonJoint right_hip\n\
body_msgs/SkeletonJoint left_knee\n\
body_msgs/SkeletonJoint right_knee\n\
body_msgs/SkeletonJoint left_foot\n\
body_msgs/SkeletonJoint right_foot\n\
\n\
================================================================================\n\
MSG: body_msgs/SkeletonJoint\n\
geometry_msgs/Point position\n\
float32 confidence\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const ::body_msgs::Skeletons_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::body_msgs::Skeletons_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.skeletons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Skeletons_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::body_msgs::Skeletons_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::body_msgs::Skeletons_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "skeletons[]" << std::endl;
    for (size_t i = 0; i < v.skeletons.size(); ++i)
    {
      s << indent << "  skeletons[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::body_msgs::Skeleton_<ContainerAllocator> >::stream(s, indent + "    ", v.skeletons[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BODY_MSGS_MESSAGE_SKELETONS_H
