<?xml version="1.0"?> 
<robot name="robotArm" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Formula according to https://en.wikipedia.org/wiki/List_of_moment_of_inertia_tensors for cylinder -->
<xacro:macro name="cyl_inertia" params="mass r h ">
    <mass value="${mass}"/>
    <inertia ixx="${0.083333 * mass * (3*r*r + h*h)}" ixy="0" ixz="0"
             iyy="${0.083333 * mass * (3*r*r + h*h)}" iyz="0"
             izz="${0.5*mass*r*r}" />
</xacro:macro>

<!-- Constants for robot dimensions -->
<xacro:property name="PI"           value="3.1415926535897931"/>
<xacro:property name="scale"        value="1" /> <!-- scale -->

<xacro:property name="mass"         value="${1 * scale}"    /> <!-- arbitrary value for mass -->
<xacro:property name="mass_divider" value="1"                /> <!-- mass divider -->
<xacro:property name="radius_hor_2" value="${1 * radius2}" />
<xacro:property name="radius_hor_3" value="${1 * radius3}" />

<xacro:property name="baseLength"   value="${0.2 * scale}"   /> <!-- base_link -->
<xacro:property name="base_radius"  value="${radius1}"       />

<xacro:property name="length1"      value="${0.5 * scale}"   /> <!-- body 1 -->
<xacro:property name="radius1"      value="${0.1 * scale}"   />

<xacro:property name="length10"     value="${2*radius1}"     /> <!-- body 10 -->
<xacro:property name="length2"      value="${0.5 * scale}"   /> <!-- body 2 -->
<xacro:property name="radius2"      value="${0.1 * scale}"   />

<xacro:property name="length20"     value="${2*radius1}"     /> <!-- body 20 -->
<xacro:property name="length3"      value="${0.05 * scale}"  /> <!-- body 3 -->
<xacro:property name="radius3"      value="${0.1 * scale}"  />

<xacro:property name="damping"      value="1" />             <!-- Damping -->
<xacro:property name="axel_offset"  value="0" />             <!-- Space btw top of beam and the each joint -->

<!-- Import all Gazebo-customization elements, including Gazebo colors -->
<xacro:include filename="$(find my_arm)/models/myArm2.gazebo" />
<!-- Import Rviz colors -->
<xacro:include filename="$(find my_arm)/models/materials.xacro" />

<!---............................. Link Definitions ................................-->
<!--
<link name="root"/>

<joint name="root_joint" type="fixed">
    <parent link="root"/>
    <child link="base_link"/>
</joint>
-->

<!---............................. BASE LINK WHITE ................................-->
<link name="base_link">
    <collision> <!-- collision -->
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder length="${baseLength}" radius="${base_radius}"/>
        </geometry>
    </collision>
    <visual>    <!-- visual -->
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder length="${baseLength}" radius="${base_radius}"/>
        </geometry>
        <material name ="white"/>
    </visual>
    <!--
    <inertial>  The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <xacro:cyl_inertia mass="${mass/mass_divider}" h="${baseLength}" r="${base_radius}"/>
    </inertial>
    -->
</link>

<!---............................. BASE JOINT REVOLUTE Z ................................-->
<joint name="base_joint" type="revolute">
    <parent link="base_link"/>
    <child link="body1"/>
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="0 0 ${baseLength/2+length1/2}"/> <!-- z - offset (difference between two joint center) (Base link + Link1) length/2 -->
    <limit effort="1000.0" lower="-2.96" upper="2.96" velocity="0.5"/>
    <dynamics damping="${damping}"/>
</joint>

<!---............................. LINK 1 BLUE ................................-->
<link name="body1">
    <collision> <!-- collision -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${length1}" radius="${radius1}"/>
        </geometry>
    </collision>
    <visual>    <!-- visual -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${length1}" radius="${radius1}"/>
        </geometry>
        <material name ="blue"/>
    </visual>
    <inertial>  <!-- inertial -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <xacro:cyl_inertia mass="${mass/mass_divider}" h="${length1}" r="${radius1}"/>
    </inertial>
</link>

<!---............................. JOINT 10 CONTINUOUS AROUND Y ................................-->
<joint name="j10" type="continuous">
    <parent link="body1"/>
    <child link="body10"/>
    <origin xyz="0 ${axel_offset} ${length1/2+radius_hor_2}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-2.96" upper="2.96" velocity="0.5"/>
    <dynamics damping="${damping}"/>
</joint>

<!---............................. LINK 10 WHITE ................................-->
<link name="body10">
    <collision> <!-- collision -->
        <origin rpy="${PI/2} 0 0" xyz="0 0 0"/> <!-- Due to being rotated around X, z as 0 -->
        <geometry>
            <cylinder length="${length10}" radius="${radius_hor_2}"/> <!-- Double the diameter of link cylinder-->
        </geometry>
    </collision>
    <visual>    <!-- visual -->
        <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${length10}" radius="${radius_hor_2}"/> <!-- Double the diameter of link cylinder-->
        </geometry>
        <material name ="white"/>
    </visual>
    <inertial>  <!-- inertial -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <xacro:cyl_inertia mass="${mass/mass_divider}" h="${length10}" r="${radius_hor_2}"/>
    </inertial>
</link>

<!---............................. JOINT 1 FIXED ................................-->
<joint name="j1" type="fixed">
    <parent link="body10"/>
    <child link="body2"/>
    <origin xyz="0 ${axel_offset} 0" rpy="0 0 0"/>
    <!-- <axis xyz="0 1 0"/> -->

    <limit effort="1000.0" lower="-2.96" upper="2.96" velocity="0.5"/>
    <dynamics damping="${damping}"/>
</joint>

<!---............................. LINK 2 GREEN .......................................-->
<link name="body2">
    <collision> <!-- collision -->
        <origin rpy="0 0 0" xyz="0 0 ${radius_hor_2+length2/2}"/>
        <geometry>
            <cylinder length="${length2}" radius="${radius2}"/>
        </geometry>
    </collision>
    <visual>    <!-- visual -->
        <origin rpy="0 0 0" xyz="0 0 ${radius_hor_2+length2/2}"/>
        <geometry>
            <cylinder length="${length2}" radius="${radius2}"/>
        </geometry>
        <material name ="green"/>
    </visual>
    <inertial>  <!-- inertial -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <xacro:cyl_inertia mass="${mass/mass_divider}" h="${length2}" r="${radius2}"/>
    </inertial>
</link>

<!---............................. JOINT 20 CONTINUOUS AROUND Y ................................-->
<joint name="j20" type="continuous">
    <parent link="body2"/>
    <child link="body20"/>
    <origin xyz="0 ${axel_offset} ${radius_hor_2 + length2 + radius_hor_3}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-2.96" upper="2.96" velocity="0.5"/>
    <dynamics damping="${damping}"/>
</joint>

<!---............................. LINK 20 WHITE ................................-->
<link name="body20">
    <collision> <!-- collision -->
        <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${length20}" radius="${radius_hor_3}"/> <!-- Double the diameter of link cylinder-->
        </geometry>
    </collision>
    <visual>    <!-- visual -->
        <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${length20}" radius="${radius_hor_3}"/> <!-- Double the diameter of link cylinder-->
        </geometry>
        <material name ="white"/>
    </visual>
    <inertial>  <!-- inertial -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <xacro:cyl_inertia mass="${mass/mass_divider}" h="${length20}" r="${radius_hor_3}"/>
    </inertial>
</link>

<!---............................. JOINT 2 FIXED ................................-->
<joint name="j2" type="fixed">
    <parent link="body20"/>
    <child link="body3"/>
    <origin xyz="0 ${axel_offset} 0" rpy="0 0 0"/>
    <!--<axis xyz="0 1 0"/> -->

    <limit effort="1000.0" lower="-2.96" upper="2.96" velocity="0.5"/>
    <dynamics damping="${damping}"/>
</joint>

<!---............................. LINK 3 GREEN .......................................-->
<link name="body3">
    <collision> <!-- collision -->
        <origin rpy="0 0 0" xyz="0 0 ${radius_hor_3+length3/2}"/>
        <geometry>
            <cylinder length="${length3}" radius="${radius3}"/>
        </geometry>
    </collision>
    <visual>    <!-- visual -->
        <origin rpy="0 0 0" xyz="0 0 ${radius_hor_3+length3/2}"/>
        <geometry>
            <cylinder length="${length3}" radius="${radius3}"/>
        </geometry>
        <material name ="green"/>
    </visual>
    <inertial>  <!-- inertial -->
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <xacro:cyl_inertia mass="${mass/mass_divider}" h="${length3}" r="${radius3}"/>
    </inertial>
</link>

<!---............................. JOINT 3 REVOLUTE Z ................................-->
<joint name="j3" type="revolute">
    <parent link="body3"/>
    <child link="brHand"/>
    <origin xyz="0 ${axel_offset} ${radius_hor_3+length3}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-2.96" upper="2.96" velocity="0.5"/>
    <dynamics damping="${2 * damping}"/>
</joint>

<!---............................. HAND .............................................. -->

  <link name="brHand">
    <inertial>
      <origin
        xyz="-1.53444878605399E-05 -0.00277693660903533 0.0352882290973172"
        rpy="0 0 0" />
      <mass
        value="0.377966381303299" />
      <inertia
        ixx="0.000427326373018601"
        ixy="2.6443337984506E-07"
        ixz="-2.02908063714989E-07"
        iyy="0.000361316175967098"
        iyz="-3.0792687327603E-05"
        izz="0.000376798128588446" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/base_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/base_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="finger_1_prox_joint" type="revolute">
    <parent
      link="brHand" />
    <child
      link="finger_1_prox_link" />
    <origin
      xyz="0.025 0 0.0415"
      rpy="0 2.7051E-17 -1.5708" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-3.141"
      upper="0"
      effort="0"
      velocity="0" />
    <dynamics damping="${damping}"/>
  </joint>
  <link
    name="finger_1_prox_link">
    <inertial>
      <origin
        xyz="-0.0288648917008988 9.98379746692153E-05 0.0171253477569802"
        rpy="0 0 0" />
      <mass
        value="56143.0626955765" />
      <inertia
        ixx="10.4484040652085"
        ixy="-0.117861448219975"
        ixz="-5.31613760585343"
        iyy="33.9552353012776"
        iyz="0.0780041192837706"
        izz="29.3669090518615" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_1_prox_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_1_prox_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
    </collision>
  </link>
  <link
    name="finger_1_med_liink">
    <inertial>
      <origin
        xyz="-0.030918176135544 0.0019693024932544 0.000743369842666108"
        rpy="0 0 0" />
      <mass
        value="31321.1214212939" />
      <inertia
        ixx="2.18512832127284"
        ixy="-0.844484268309696"
        ixz="0.0135401272401385"
        iyy="17.3596441998536"
        iyz="-0.001126692167519"
        izz="17.7656644395659" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_1_med_liink.STL" scale="1.5 1.5 1.5"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_1_med_liink.STL" scale="1.5 1.5 1.5"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="finger_1_med_joint"
    type="revolute">
    <origin
      xyz="-0.05 0 0.0339"
      rpy="1.5708 -8.8281E-17 0" />
    <parent
      link="finger_1_prox_link" />
    <child
      link="finger_1_med_liink" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-2.44"
      upper="0"
      effort="0"
      velocity="0" />
    <dynamics damping="${damping}"/>
  </joint>
  <link
    name="finger_1_dist_link">
    <inertial>
      <origin
        xyz="-0.018331495851456 0.017563370050582 0.000497127783315291"
        rpy="0 0 0" />
      <mass
        value="19342.3312257343" />
      <inertia
        ixx="3.67466110522623"
        ixy="-2.57800680786605"
        ixz="-0.0345727635031181"
        iyy="4.08727012680705"
        iyz="0.0329223427372985"
        izz="5.99395386650428" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_1_dist_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.898039215686275 0.917647058823529 0.929411764705882 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_1_dist_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="finger_1_dist_joint"
    type="revolute">
    <origin
      xyz="-0.069936 0.003 0"
      rpy="1.6787E-18 -3.6382E-15 -6.1073E-33" />
    <parent
      link="finger_1_med_liink" />
    <child
      link="finger_1_dist_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-0.785"
      upper="0"
      effort="0"
      velocity="0" />
    <dynamics damping="${damping}"/>
  </joint>
  <link
    name="finger_2_prox_link">
    <inertial>
      <origin
        xyz="-0.0288648917008987 9.98379746692118E-05 0.0171253477569802"
        rpy="0 0 0" />
      <mass
        value="56143.0626955765" />
      <inertia
        ixx="10.4484040652085"
        ixy="-0.117861448219975"
        ixz="-5.31613760585343"
        iyy="33.9552353012776"
        iyz="0.0780041192837701"
        izz="29.3669090518615" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_2_prox_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_2_prox_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="finger_2_prox_joint"
    type="revolute">
    <origin
      xyz="-0.025 0 0.0415"
      rpy="0 2.7051E-17 -1.5708" />
    <parent
      link="brHand" />
    <child
      link="finger_2_prox_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="0"
      upper="3.141"
      effort="0"
      velocity="0" />
    <dynamics damping="${damping}"/>
  </joint>
  <link
    name="finger_2_med_link">
    <inertial>
      <origin
        xyz="-0.0309061378225848 0.00214997948654991 0.000743369814045599"
        rpy="0 0 0" />
      <mass
        value="31321.1215499126" />
      <inertia
        ixx="2.19551825824831"
        ixy="-0.933117181988174"
        ixz="0.0135333166873642"
        iyy="17.3492542935561"
        iyz="-0.00120585854514789"
        izz="17.7656644132238" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_2_med_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_2_med_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="finger_2_med_joint"
    type="revolute">
    <origin
      xyz="-0.05 0 0.0339"
      rpy="1.5708 -8.8281E-17 0" />
    <parent
      link="finger_2_prox_link" />
    <child
      link="finger_2_med_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-2.44"
      upper="0"
      effort="0"
      velocity="0" />
    <dynamics damping="${damping}"/>
  </joint>
  <link
    name="finger_2_dist_link">
    <inertial>
      <origin
        xyz="-0.0181940669984822 0.017705695005231 0.000497127783261171"
        rpy="0 0 0" />
      <mass
        value="19342.3313295693" />
      <inertia
        ixx="3.71486604025429"
        ixy="-2.58090906930852"
        ixz="-0.0343151446338957"
        iyy="4.04706522522361"
        iyz="0.0331907761165059"
        izz="5.99395390717116" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_2_dist_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.898039215686275 0.917647058823529 0.929411764705882 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_2_dist_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="finger_2_dist_joint"
    type="revolute">
    <origin
      xyz="-0.069917 0.0034087 0"
      rpy="-3.1382E-17 -2.3229E-16 0" />
    <parent
      link="finger_2_med_link" />
    <child
      link="finger_2_dist_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-0.785"
      upper="0"
      effort="0"
      velocity="0" />
    <dynamics damping="${damping}"/>
  </joint>
  <link
    name="finger_3_med_link">
    <inertial>
      <origin
        xyz="-0.0309181761355441 0.00196930249325443 0.000743369842666415"
        rpy="0 0 0" />
      <mass
        value="31321.121421294" />
      <inertia
        ixx="2.18512832127284"
        ixy="-0.844484268309696"
        ixz="0.0135401272400822"
        iyy="17.3596441998537"
        iyz="-0.0011266921675151"
        izz="17.7656644395659" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_3_med_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_3_med_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="finger_3_med_joint"
    type="revolute">
    <origin
      xyz="0 -0.05 0.0754"
      rpy="1.5708 6.123E-17 1.5708" />
    <parent
      link="brHand" />
    <child
      link="finger_3_med_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-2.44"
      upper="0"
      effort="0"
      velocity="0" />
    <dynamics damping="${damping}"/>
  </joint>
  <link
    name="finger_3_dist_link">
    <inertial>
      <origin
        xyz="-0.0183314958518909 0.0175633700501297 0.000497127783323787"
        rpy="0 0 0" />
      <mass
        value="19342.3312257343" />
      <inertia
        ixx="3.67466110509902"
        ixy="-2.57800680785588"
        ixz="-0.0345727635040649"
        iyy="4.08727012693427"
        iyz="0.0329223427365976"
        izz="5.99395386650428" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_3_dist_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.898039215686275 0.917647058823529 0.929411764705882 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://my_arm/meshes/finger_3_dist_link.STL" scale="1.5 1.5 1.5"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="finger_3_dist_joint"
    type="revolute">
    <origin
      xyz="-0.069936 0.003 0"
      rpy="6.0427E-17 -6.7283E-18 -4.0657E-34" />
    <parent
      link="finger_3_med_link" />
    <child
      link="finger_3_dist_link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-0.785"
      upper="0"
      effort="0"
      velocity="0" />
    <dynamics damping="${damping}"/>
  </joint>

</robot>
